"""orders, payment methods and payments

Revision ID: 31e6c517d951
Revises: e530d09801a1
Created: 2026-08-22 14:38:31.513632

REVIEW BEFORE APPLYING. Autogenerate is a first draft, not an answer — it
misses renames (it sees a drop plus an add, which loses data), and it cannot
know about constraints you meant to add. Read every line.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '31e6c517d951'
down_revision: str | None = 'e530d09801a1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('buyer_name', sa.String(length=120), nullable=False),
    sa.Column('buyer_phone', sa.String(length=20), nullable=False),
    sa.Column('whatsapp_opt_in', sa.Boolean(), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('delivery_note', sa.Text(), nullable=True),
    sa.Column('subtotal_kes', sa.Integer(), nullable=False),
    sa.Column('delivery_fee_kes', sa.Integer(), nullable=False),
    sa.Column('total_kes', sa.Integer(), nullable=False),
    sa.Column('paid_to_kind', sa.String(length=20), nullable=False),
    sa.Column('paid_to_number', sa.String(length=20), nullable=False),
    sa.Column('paid_to_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'paid') = (paid_at IS NOT NULL)", name='ck_orders_paid_has_timestamp'),
    sa.CheckConstraint("paid_to_kind IN ('pochi', 'till', 'paybill')", name='ck_orders_paid_to_kind_valid'),
    sa.CheckConstraint("status IN ('pending', 'awaiting_confirmation', 'paid', 'cancelled', 'failed')", name='ck_orders_status_valid'),
    sa.CheckConstraint('delivery_fee_kes >= 0', name='ck_orders_delivery_fee_non_negative'),
    sa.CheckConstraint('subtotal_kes > 0', name='ck_orders_subtotal_positive'),
    sa.CheckConstraint('total_kes = subtotal_kes + delivery_fee_kes', name='ck_orders_total_is_subtotal_plus_delivery'),
    sa.CheckConstraint('total_kes > 0', name='ck_orders_total_positive'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index('ix_orders_seller_created', 'orders', ['seller_id', 'created_at'], unique=False)
    op.create_index('ix_orders_seller_status', 'orders', ['seller_id', 'status'], unique=False)
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=120), nullable=True),
    sa.Column('account_reference', sa.String(length=40), nullable=True),
    sa.Column('stk_shortcode', sa.String(length=20), nullable=True),
    sa.Column('consumer_key_enc', sa.Text(), nullable=True),
    sa.Column('consumer_secret_enc', sa.Text(), nullable=True),
    sa.Column('passkey_enc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind <> 'pochi' OR ( stk_shortcode IS NULL AND consumer_key_enc IS NULL AND consumer_secret_enc IS NULL AND passkey_enc IS NULL)", name='ck_payment_methods_pochi_has_no_stk'),
    sa.CheckConstraint("kind IN ('pochi', 'till', 'paybill')", name='ck_payment_methods_kind_valid'),
    sa.CheckConstraint('(stk_shortcode IS NULL AND consumer_key_enc IS NULL AND consumer_secret_enc IS NULL AND passkey_enc IS NULL) OR (stk_shortcode IS NOT NULL AND consumer_key_enc IS NOT NULL AND consumer_secret_enc IS NOT NULL AND passkey_enc IS NOT NULL)', name='ck_payment_methods_stk_credentials_complete'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('method_kind', sa.String(length=20), nullable=False),
    sa.Column('amount_kes', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('checkout_request_id', sa.String(length=64), nullable=True),
    sa.Column('merchant_request_id', sa.String(length=64), nullable=True),
    sa.Column('result_code', sa.Integer(), nullable=True),
    sa.Column('result_desc', sa.Text(), nullable=True),
    sa.Column('raw_callback', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('claimed_code', sa.String(length=20), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mpesa_receipt', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method_kind IN ('pochi', 'till', 'paybill')", name='ck_payments_method_kind_valid'),
    sa.CheckConstraint('amount_kes > 0', name='ck_payments_amount_positive'),
    sa.CheckConstraint('confirmed_at IS NULL OR mpesa_receipt IS NOT NULL', name='ck_payments_confirmed_has_receipt'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkout_request_id'),
    sa.UniqueConstraint('checkout_request_id', name='uq_payments_checkout_request')
    )
    op.create_index('ix_payments_order', 'payments', ['order_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('unit_price_kes', sa.Integer(), nullable=False),
    sa.Column('unit_quantity', sa.Integer(), nullable=True),
    sa.Column('unit_label', sa.String(length=32), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('selected_variant', sa.String(length=80), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('line_total_kes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(unit_quantity IS NULL) = (unit_label IS NULL)', name='ck_order_items_unit_quantity_and_label_together'),
    sa.CheckConstraint('line_total_kes = unit_price_kes * quantity', name='ck_order_items_line_total_is_price_times_quantity'),
    sa.CheckConstraint('quantity > 0', name='ck_order_items_quantity_positive'),
    sa.CheckConstraint('unit_price_kes > 0', name='ck_order_items_unit_price_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_items_order', 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_items_order', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_payments_order', table_name='payments')
    op.drop_table('payments')
    op.drop_table('payment_methods')
    op.drop_index('ix_orders_seller_status', table_name='orders')
    op.drop_index('ix_orders_seller_created', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
