"""parsed_media: each forwarded image read once ever

Revision ID: 1e60b4caca1b
Revises: 2bc6af85a0a5
Created: 2026-08-25 05:32:19.346086

REVIEW BEFORE APPLYING. Autogenerate is a first draft, not an answer — it
misses renames (it sees a drop plus an add, which loses data), and it cannot
know about constraints you meant to add. Read every line.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '1e60b4caca1b'
down_revision: str | None = '2bc6af85a0a5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_media_id', sa.String(length=128), nullable=False),
    sa.Column('draft', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(draft IS NULL) <> (error IS NULL)', name='ck_parsed_media_draft_xor_error'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_media_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parsed_media')
    # ### end Alembic commands ###
