"""social account ownership verification

Revision ID: cc2fff8a3fd1
Revises: d6cdd06e2776
Created: 2026-08-12 20:01:37.142964

REVIEW BEFORE APPLYING. Autogenerate is a first draft, not an answer — it
misses renames (it sees a drop plus an add, which loses data), and it cannot
know about constraints you meant to add. Read every line.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'cc2fff8a3fd1'
down_revision: str | None = 'd6cdd06e2776'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_accounts', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('social_accounts', sa.Column('verification_method', sa.String(length=20), nullable=True))
    op.add_column('social_accounts', sa.Column('verification_code', sa.String(length=32), nullable=True))
    op.add_column('social_accounts', sa.Column('verification_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_accounts', 'verification_expires_at')
    op.drop_column('social_accounts', 'verification_code')
    op.drop_column('social_accounts', 'verification_method')
    op.drop_column('social_accounts', 'verified_at')
    # ### end Alembic commands ###
