"""account claims and verified only social accounts

Revision ID: 0f28636c2759
Revises: cc2fff8a3fd1
Created: 2026-08-12 20:59:47.769700

REVIEW BEFORE APPLYING. Autogenerate is a first draft, not an answer — it
misses renames (it sees a drop plus an add, which loses data), and it cannot
know about constraints you meant to add. Read every line.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0f28636c2759'
down_revision: str | None = 'cc2fff8a3fd1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('handle', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("platform IN ('tiktok', 'instagram', 'facebook', 'jumia')", name='ck_account_claims_platform_valid'),
    sa.CheckConstraint('attempts >= 0', name='ck_account_claims_attempts_non_negative'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_id', 'platform', name='uq_account_claims_seller_platform')
    )
    op.create_index('ix_account_claims_expires', 'account_claims', ['expires_at'], unique=False)
    op.create_index('ix_account_claims_seller', 'account_claims', ['seller_id'], unique=False)
    op.alter_column('social_accounts', 'verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('social_accounts', 'verification_method',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('social_accounts', 'verification_expires_at')
    op.drop_column('social_accounts', 'verification_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_accounts', sa.Column('verification_code', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('social_accounts', sa.Column('verification_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('social_accounts', 'verification_method',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('social_accounts', 'verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index('ix_account_claims_seller', table_name='account_claims')
    op.drop_index('ix_account_claims_expires', table_name='account_claims')
    op.drop_table('account_claims')
    # ### end Alembic commands ###
