"""storefront: carts, product category and compare-at price

Revision ID: e530d09801a1
Revises: 7bde9231c6a0
Created: 2026-08-22 13:52:55.502331

REVIEW BEFORE APPLYING. Autogenerate is a first draft, not an answer — it
misses renames (it sees a drop plus an add, which loses data), and it cannot
know about constraints you meant to add. Read every line.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'e530d09801a1'
down_revision: str | None = '7bde9231c6a0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_carts_seller', 'carts', ['seller_id'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('selected_variant', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_cart_items_quantity_positive'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'product_id', 'selected_variant', name='uq_cart_items_line')
    )
    op.add_column('products', sa.Column('compare_at_price_kes', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('category', sa.String(length=40), nullable=True))
    op.create_index('ix_products_seller_category', 'products', ['seller_id', 'category'], unique=False)
    # ### end Alembic commands ###

    # ADDED BY HAND. Autogenerate does not detect CheckConstraints added to an
    # existing table, so this rail would have lived only in the Python model —
    # which is precisely the failure mode `models/__init__.py` warns about: a
    # constraint the database does not actually hold is a comment, not a rail.
    #
    # A "was" price must exceed the real one and cannot float free of it, or the
    # discount badge advertises a saving that is zero, negative, or measured
    # against nothing.
    op.create_check_constraint(
        'ck_products_compare_at_exceeds_price',
        'products',
        'compare_at_price_kes IS NULL'
        ' OR (price_kes IS NOT NULL AND compare_at_price_kes > price_kes)',
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Dropped first: the constraint references the column removed below.
    op.drop_constraint('ck_products_compare_at_exceeds_price', 'products', type_='check')
    op.drop_index('ix_products_seller_category', table_name='products')
    op.drop_column('products', 'category')
    op.drop_column('products', 'compare_at_price_kes')
    op.drop_table('cart_items')
    op.drop_index('ix_carts_seller', table_name='carts')
    op.drop_table('carts')
    # ### end Alembic commands ###
