"""product unit quantity label and price evidence

Revision ID: 588f6c5577d0
Revises: 3bbf0cbc3f71
Created: 2026-08-08 15:35:15.966989

REVIEW BEFORE APPLYING. Autogenerate is a first draft, not an answer — it
misses renames (it sees a drop plus an add, which loses data), and it cannot
know about constraints you meant to add. Read every line.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '588f6c5577d0'
down_revision: str | None = '3bbf0cbc3f71'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('unit_quantity', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('unit_label', sa.String(length=32), nullable=True))
    op.add_column('products', sa.Column('price_evidence', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price_evidence')
    op.drop_column('products', 'unit_label')
    op.drop_column('products', 'unit_quantity')
    # ### end Alembic commands ###
