"""posts and metric snapshots

Revision ID: 8a73215c229c
Revises: 3c58aeb758b4
Created: 2026-08-19 18:42:15.113761

Reviewed 2026-08-19. Three new tables and one new column. Purely additive:
nothing existing is dropped, renamed or rewritten, so it is safe to apply to a
database with live rows.

WHY THESE TABLES. ``Post.views`` is overwritten on every sync, so no table of
current values can answer "am I growing?". The snapshots can — and THEIR
HISTORY CANNOT BE BACKFILLED, because TikTok will not say what a post had last
Tuesday and Apify only ever returns today. That is why this shipped before the
page that displays it.

``products.post_id`` is nullable and stays that way: a manual photo upload is a
real product with no post behind it. It is the first half of separating content
from commerce — see docs/BUILD_ORDER.md step 2.

TWO EDITS TO THE AUTOGENERATED DRAFT. Alembic emitted the unique constraint and
the foreign key on products.post_id with ``None`` for a name, which Postgres
accepts on the way up and cannot act on going down — ``drop_constraint(None)``
raises. Both are named here so the downgrade actually runs.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '8a73215c229c'
down_revision: str | None = '3c58aeb758b4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table('account_metric_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_account_id', sa.Integer(), nullable=False),
    sa.Column('captured_on', sa.Date(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('total_likes', sa.Integer(), nullable=False),
    sa.CheckConstraint('follower_count >= 0 AND post_count >= 0 AND total_likes >= 0', name='ck_account_snapshots_non_negative'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_account_id', 'captured_on', name='uq_account_snapshot_per_day')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_account_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('platform_post_id', sa.String(length=64), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('post_url', sa.String(length=500), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('reposts', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("platform IN ('tiktok', 'instagram', 'facebook', 'jumia', 'manual')", name='ck_posts_platform_valid'),
    sa.CheckConstraint('views >= 0 AND likes >= 0 AND comments >= 0 AND shares >= 0 AND saves >= 0 AND reposts >= 0', name='ck_posts_metrics_non_negative'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_post_id', name='uq_posts_platform_post')
    )
    op.create_index('ix_posts_account_posted', 'posts', ['social_account_id', 'posted_at'], unique=False)
    op.create_table('post_metric_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('captured_on', sa.Date(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('reposts', sa.Integer(), nullable=False),
    sa.CheckConstraint('views >= 0 AND likes >= 0 AND comments >= 0 AND shares >= 0 AND saves >= 0 AND reposts >= 0', name='ck_post_snapshots_non_negative'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'captured_on', name='uq_post_snapshot_per_day')
    )
    op.add_column('products', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_unique_constraint("uq_products_post_id", "products", ["post_id"])
    op.create_foreign_key(
        "fk_products_post_id", "products", "posts", ["post_id"], ["id"], ondelete="SET NULL"
    )


def downgrade() -> None:
    op.drop_constraint("fk_products_post_id", "products", type_="foreignkey")
    op.drop_constraint("uq_products_post_id", "products", type_="unique")
    op.drop_column('products', 'post_id')
    op.drop_table('post_metric_snapshots')
    op.drop_index('ix_posts_account_posted', table_name='posts')
    op.drop_table('posts')
    op.drop_table('account_metric_snapshots')
