"""sellers products scrape_jobs with rails

Revision ID: 3bbf0cbc3f71
Revises: f33154a36521
Created: 2026-08-08 10:18:39.412600

REVIEW BEFORE APPLYING. Autogenerate is a first draft, not an answer — it
misses renames (it sees a drop plus an add, which loses data), and it cannot
know about constraints you meant to add. Read every line.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '3bbf0cbc3f71'
down_revision: str | None = 'f33154a36521'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tiktok_handle', sa.String(length=64), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name='ck_sellers_slug_format'),
    sa.CheckConstraint('follower_count >= 0', name='ck_sellers_follower_count_non_negative'),
    sa.CheckConstraint('is_published = false OR whatsapp_number IS NOT NULL', name='ck_sellers_published_needs_whatsapp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('tiktok_handle')
    )
    op.create_index('ix_sellers_slug', 'sellers', ['slug'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tiktok_video_id', sa.String(length=64), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('raw_caption', sa.Text(), nullable=True),
    sa.Column('hashtags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_kes', sa.Integer(), nullable=True),
    sa.Column('sizes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parse_confidence', sa.Float(), nullable=True),
    sa.Column('price_source', sa.String(length=20), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("price_source IS NULL OR price_source IN ('caption', 'cover_image', 'video', 'seller')", name='ck_products_price_source_valid'),
    sa.CheckConstraint("source <> 'manual' OR tiktok_video_id IS NULL", name='ck_products_manual_has_no_video_id'),
    sa.CheckConstraint("source IN ('tiktok_profile', 'tiktok_link', 'manual')", name='ck_products_source_valid'),
    sa.CheckConstraint("status <> 'published' OR price_kes IS NOT NULL", name='ck_products_published_requires_price'),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name='ck_products_status_valid'),
    sa.CheckConstraint('parse_confidence IS NULL OR (parse_confidence >= 0 AND parse_confidence <= 1)', name='ck_products_confidence_range'),
    sa.CheckConstraint('price_kes IS NULL OR price_kes <= 10000000', name='ck_products_price_plausible'),
    sa.CheckConstraint('price_kes IS NULL OR price_kes > 0', name='ck_products_price_positive'),
    sa.CheckConstraint('stock >= 0', name='ck_products_stock_non_negative'),
    sa.CheckConstraint('views >= 0 AND likes >= 0 AND comments >= 0 AND shares >= 0', name='ck_products_metrics_non_negative'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tiktok_video_id')
    )
    op.create_index('ix_products_seller_confidence', 'products', ['seller_id', 'parse_confidence'], unique=False)
    op.create_index('ix_products_seller_source', 'products', ['seller_id', 'source'], unique=False)
    op.create_index('ix_products_seller_status', 'products', ['seller_id', 'status'], unique=False)
    op.create_table('scrape_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=False),
    sa.Column('products_upserted', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status <> 'failed' OR error IS NOT NULL", name='ck_scrape_jobs_failed_needs_error'),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'failed')", name='ck_scrape_jobs_status_valid'),
    sa.CheckConstraint('video_count >= 0 AND products_upserted >= 0', name='ck_scrape_jobs_counts_non_negative'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scrape_jobs_seller_started', 'scrape_jobs', ['seller_id', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scrape_jobs_seller_started', table_name='scrape_jobs')
    op.drop_table('scrape_jobs')
    op.drop_index('ix_products_seller_status', table_name='products')
    op.drop_index('ix_products_seller_source', table_name='products')
    op.drop_index('ix_products_seller_confidence', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_sellers_slug', table_name='sellers')
    op.drop_table('sellers')
    # ### end Alembic commands ###
