"""wa_conversations: where a buyer is in the chat

Revision ID: 127240937cde
Revises: 3dc8a2292233
Created: 2026-08-25 04:34:06.507366

REVIEW BEFORE APPLYING. Autogenerate is a first draft, not an answer — it
misses renames (it sees a drop plus an add, which loses data), and it cannot
know about constraints you meant to add. Read every line.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '127240937cde'
down_revision: str | None = '3dc8a2292233'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wa_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('order_reference', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state <> 'paying' OR order_reference IS NOT NULL", name='ck_wa_conversations_paying_needs_order'),
    sa.CheckConstraint("state = 'new' OR seller_id IS NOT NULL", name='ck_wa_conversations_browsing_needs_seller'),
    sa.CheckConstraint("state IN ('new', 'browsing', 'listing', 'product', 'cart', 'address', 'paying')", name='ck_wa_conversations_state_valid'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_wa_conversations_seller_id'), 'wa_conversations', ['seller_id'], unique=False)
    op.create_index('ix_wa_conversations_updated', 'wa_conversations', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wa_conversations_updated', table_name='wa_conversations')
    op.drop_index(op.f('ix_wa_conversations_seller_id'), table_name='wa_conversations')
    op.drop_table('wa_conversations')
    # ### end Alembic commands ###
