"""wa_conversations.cart_token: the basket a chat owns

Revision ID: 2bc6af85a0a5
Revises: 127240937cde
Created: 2026-08-25 04:41:32.514213

REVIEW BEFORE APPLYING. Autogenerate is a first draft, not an answer — it
misses renames (it sees a drop plus an add, which loses data), and it cannot
know about constraints you meant to add. Read every line.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '2bc6af85a0a5'
down_revision: str | None = '127240937cde'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wa_conversations', sa.Column('cart_token', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wa_conversations', 'cart_token')
    # ### end Alembic commands ###
