"""generalise for multi-platform accounts and add logins

Revision ID: d6cdd06e2776
Revises: 588f6c5577d0
Created: 2026-08-09 10:23:31.882353

REVIEW BEFORE APPLYING. Autogenerate is a first draft, not an answer — it
misses renames (it sees a drop plus an add, which loses data), and it cannot
know about constraints you meant to add. Read every line.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'd6cdd06e2776'
down_revision: str | None = '588f6c5577d0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("phone IS NULL OR phone ~ '^254[17][0-9]{8}$'", name='ck_accounts_phone_format'),
    sa.CheckConstraint("position('@' in email) > 1", name='ck_accounts_email_shape'),
    sa.CheckConstraint('email = lower(email)', name='ck_accounts_email_lowercase'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('ix_accounts_email', 'accounts', ['email'], unique=False)
    op.create_table('social_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('handle', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("platform <> 'manual'", name='ck_social_accounts_not_manual'),
    sa.CheckConstraint("platform IN ('tiktok', 'instagram', 'facebook', 'jumia')", name='ck_social_accounts_platform_valid'),
    sa.CheckConstraint('follower_count >= 0 AND post_count >= 0', name='ck_social_accounts_counts_non_negative'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'handle', name='uq_social_accounts_platform_handle'),
    sa.UniqueConstraint('seller_id', 'platform', name='uq_social_accounts_seller_platform')
    )
    op.create_index('ix_social_accounts_seller', 'social_accounts', ['seller_id'], unique=False)
    op.add_column('products', sa.Column('platform', sa.String(length=20), nullable=False))
    op.add_column('products', sa.Column('ingest_method', sa.String(length=20), nullable=False))
    op.add_column('products', sa.Column('social_account_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('platform_post_id', sa.String(length=64), nullable=True))
    op.add_column('products', sa.Column('source_url', sa.String(length=500), nullable=True))
    op.drop_index(op.f('ix_products_seller_source'), table_name='products')
    op.drop_constraint(op.f('products_tiktok_video_id_key'), 'products', type_='unique')
    op.create_index('ix_products_seller_platform', 'products', ['seller_id', 'platform', 'ingest_method'], unique=False)
    op.create_unique_constraint('uq_products_platform_post', 'products', ['platform', 'platform_post_id'])
    op.create_foreign_key(None, 'products', 'social_accounts', ['social_account_id'], ['id'], ondelete='SET NULL')
    op.drop_column('products', 'source')
    op.drop_column('products', 'tiktok_video_id')
    op.drop_column('products', 'video_url')
    op.add_column('scrape_jobs', sa.Column('platform', sa.String(length=20), nullable=False))
    op.add_column('scrape_jobs', sa.Column('ingest_method', sa.String(length=20), nullable=False))
    op.drop_column('scrape_jobs', 'source')
    op.add_column('sellers', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('sellers', sa.Column('location', sa.String(length=200), nullable=True))
    op.alter_column('sellers', 'bio',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_constraint(op.f('sellers_tiktok_handle_key'), 'sellers', type_='unique')
    op.create_unique_constraint(None, 'sellers', ['account_id'])
    op.create_foreign_key(None, 'sellers', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sellers', 'follower_count')
    op.drop_column('sellers', 'tiktok_handle')
    op.drop_column('sellers', 'last_synced_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('sellers', sa.Column('tiktok_handle', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('sellers', sa.Column('follower_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sellers', type_='foreignkey')
    op.drop_constraint(None, 'sellers', type_='unique')
    op.create_unique_constraint(op.f('sellers_tiktok_handle_key'), 'sellers', ['tiktok_handle'], postgresql_nulls_not_distinct=False)
    op.alter_column('sellers', 'bio',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('sellers', 'location')
    op.drop_column('sellers', 'account_id')
    op.add_column('scrape_jobs', sa.Column('source', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('scrape_jobs', 'ingest_method')
    op.drop_column('scrape_jobs', 'platform')
    op.add_column('products', sa.Column('video_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('tiktok_video_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('source', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint('uq_products_platform_post', 'products', type_='unique')
    op.drop_index('ix_products_seller_platform', table_name='products')
    op.create_unique_constraint(op.f('products_tiktok_video_id_key'), 'products', ['tiktok_video_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_products_seller_source'), 'products', ['seller_id', 'source'], unique=False)
    op.drop_column('products', 'source_url')
    op.drop_column('products', 'platform_post_id')
    op.drop_column('products', 'social_account_id')
    op.drop_column('products', 'ingest_method')
    op.drop_column('products', 'platform')
    op.drop_index('ix_social_accounts_seller', table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index('ix_accounts_email', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
