"""inbound whatsapp messages

Revision ID: 3dc8a2292233
Revises: 4c33b1e4d69f
Created: 2026-08-23 15:32:53.936127

REVIEW BEFORE APPLYING. Autogenerate is a first draft, not an answer — it
misses renames (it sees a drop plus an add, which loses data), and it cannot
know about constraints you meant to add. Read every line.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '3dc8a2292233'
down_revision: str | None = '4c33b1e4d69f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wa_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=64), nullable=False),
    sa.Column('from_number', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('media_count', sa.Integer(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('media_count >= 0', name='ck_wa_messages_media_count_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_message_id')
    )
    op.create_index('ix_wa_messages_from_created', 'wa_messages', ['from_number', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wa_messages_from_created', table_name='wa_messages')
    op.drop_table('wa_messages')
    # ### end Alembic commands ###
