"""multi-shop: many shops per account, active shop, soft delete

Revision ID: 36be1d40898d
Revises: b3d7c8e15f42
Created: 2026-09-06 13:59:35.466898

REVIEW BEFORE APPLYING. Autogenerate is a first draft, not an answer — it
misses renames (it sees a drop plus an add, which loses data), and it cannot
know about constraints you meant to add. Read every line.

WHAT THIS DOES, and why each step is safe on a live table:
  - sellers.archived_at (nullable) — the soft-delete marker for a shop; existing
    rows stay NULL (not deleted). Additive, no backfill.
  - drop UNIQUE sellers.account_id, add a plain INDEX instead — this is what
    lets one account own several shops. Dropping a uniqueness rule never
    invalidates existing rows; the index keeps account lookups fast.
  - wa_conversations.managing_shop_id (nullable FK, ON DELETE SET NULL) — the
    shop a seller is currently managing. Additive; NULL falls back to their
    primary shop in code.
The FK is given an explicit name so downgrade can drop it by name.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '36be1d40898d'
down_revision: str | None = 'b3d7c8e15f42'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('sellers_account_id_key'), 'sellers', type_='unique')
    op.create_index(op.f('ix_sellers_account_id'), 'sellers', ['account_id'], unique=False)
    op.add_column('wa_conversations', sa.Column('managing_shop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_wa_conversations_managing_shop_id_sellers',
        'wa_conversations',
        'sellers',
        ['managing_shop_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_wa_conversations_managing_shop_id_sellers', 'wa_conversations', type_='foreignkey'
    )
    op.drop_column('wa_conversations', 'managing_shop_id')
    op.drop_index(op.f('ix_sellers_account_id'), table_name='sellers')
    op.create_unique_constraint(op.f('sellers_account_id_key'), 'sellers', ['account_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('sellers', 'archived_at')
    # ### end Alembic commands ###
